//@version=4
study(title="TREND", shorttitle="TREND", resolution="")
// Getting inputs
fast_length = input(title="Fast Length", type=input.integer, defval=12)
slow_length = input(title="Slow Length", type=input.integer, defval=26)
src = input(title="Source", type=input.source, defval=close)
signal_length = input(title="Signal Smoothing", type=input.integer, minval = 1, maxval = 50, defval = 9)
sma_source = input(title="Oscillator MA Type", type=input.string, defval="EMA", options=["SMA", "EMA"])
sma_signal = input(title="Signal Line MA Type", type=input.string, defval="EMA", options=["SMA", "EMA"])
// Calculating
fast_ma = sma_source == "SMA" ? sma(src, fast_length) : ema(src, fast_length)
slow_ma = sma_source == "SMA" ? sma(src, slow_length) : ema(src, slow_length)
macd = fast_ma - slow_ma
signal = sma_signal == "SMA" ? sma(macd, signal_length) : ema(macd, signal_length)

// Plot colors
col_macd = input(#2962FF, "Up", input.color, group="Color Settings", inline="UP")
col_signal = input(#FF6D00, "Down", input.color, group="Color Settings", inline="DOWN")

macd_color = close > close[1] ? col_macd : col_signal 
his = macd - signal 
hisColor =  his > 0 ? col_macd : col_signal

plot(macd, title="MACD",color = color.new(macd_color,0))
plot(signal, title="Signal", color = color.new(hisColor,0))
